package com.example.carparkingapi.model;

public enum ActionType {
    PARKING_CAR, LEAVING_PARKING, ADDING_CAR, MODIFYING_CAR_DETAILS, DELETING_CAR, ADDING_PARKING, MODIFYING_PARKING_DETAILS, DELETING_PARKING,
    RETRIEVING_CAR, RETRIEVING_PARKING, RETRIEVING_ALL_CARS, RETRIEVING_ALL_PARKINGS, RETRIEVING_ALL_CUSTOMERS, RETRIEVING_CUSTOMER,
    RETRIEVING_ALL_CARS_FROM_PARKING, RETRIEVING_CARS_COUNT_FROM_PARKING, RETRIEVING_MOST_EXPENSIVE_CAR, RETRIEVING_MOST_EXPENSIVE_CAR_FROM_PARKING, UPDATING_CAR, UPDATING_PARKING, UPDATING_CUSTOMER, RETRIEVING_ALL_ACTIONS
}
